### ISSUE TITLE
verify daemon is injection-proof

### ISSUE THREAD

**Issue by barbieri** [ostroproject/swupd-daemon#3]
verify if the line we execute is injection-proof, that is. It may be tricky if we use "system(3)-like" calls, since it could use envvars and $() or ;. It's safer to directly call the binary giving the command array as execve().

(This is more of a reminder, didn't investigate if this is possible with current code)

**Comment by rojkov** [comment]
https://github.com/ostroproject/swupd-daemon/pull/5 uses `execvp()`
