### ISSUE TITLE
replace glib with libsystemd

### ISSUE THREAD

**Issue by barbieri** [ostroproject/swupd-daemon#4]
Since this project will be merged in swupd-client, they do not want to depend on glib but are okay with libsystemd, since systemd is a core component of both Ostro and ClearLinux.

The `sd-bus.h` is very easy to use for both client and server. See an introdution at http://0pointer.de/blog/the-new-sd-bus-api-of-systemd.html and full header at https://github.com/systemd/systemd/blob/master/src/systemd/sd-bus.h

For the main loop concept you can use other parts of libsystemd, like `sd-event.h` (https://github.com/systemd/systemd/blob/master/src/systemd/sd-event.h)

**Comment by rojkov** [comment]
the initial re-implementation has been done in https://github.com/ostroproject/swupd-daemon/pull/5
